-- Candidate trades logging schema.
-- Single source of truth — read at runtime by logging/writer.py.
-- Spec v2.6, Section 10.

CREATE TABLE IF NOT EXISTS candidate_trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp_ms                INTEGER NOT NULL,
    contract_id                 TEXT NOT NULL,
    market_open_time            TEXT NOT NULL,
    seconds_to_resolution       REAL NOT NULL,
    mlofi_value                 REAL,
    mlofi_raw_components        TEXT,
    binance_spread_percentile   REAL,
    polymarket_depth_best_ask   REAL,
    polymarket_depth_5s_change  REAL,
    polymarket_spread_5s_change REAL,
    adverse_selection_composite REAL,
    roll_15                     REAL,
    roll_50                     REAL,
    vpin_15                     REAL,
    vpin_50                     REAL,
    vwap_deviation_buy          REAL,
    vwap_deviation_sell         REAL,
    p_model                     REAL,
    p_market                    REAL,
    payout                      REAL,
    fee_t                       REAL,
    spread_t                    REAL,
    ne_t_computed               REAL,
    gate_structural_pass        INTEGER,
    gate_structural_reason      TEXT,
    gate_adverse_pass           INTEGER,
    gate_adverse_composite_value REAL,
    gate_adverse_fpr_threshold  REAL,
    gate_ne_positive            INTEGER,
    gate_sanderink_pass         INTEGER,
    gate_sanderink_pstar        REAL,
    gate_sanderink_posterior    REAL,
    gate_sanderink_n_obs        INTEGER,
    executed                    INTEGER,
    suppression_reason          TEXT,
    position_size_fraction      REAL,
    kelly_full                  REAL,
    kelly_fractional            REAL,
    t_ofi_signal_ms             INTEGER,
    t_ask_depth_drop_ms         INTEGER,
    t_ask_price_move_ms         INTEGER,
    ask_depth_at_signal         REAL,
    ask_depth_5s_after_signal   REAL,
    operational_lag_ms          INTEGER,
    mlofi_dist_psi_7d           REAL,
    mlofi_pred_psi_7d           REAL,
    feature_stability_alert     INTEGER,
    feature_stability_type      TEXT,
    resolved_direction          INTEGER,
    model_correct               INTEGER,
    ne_t_realised               REAL
);
CREATE INDEX IF NOT EXISTS idx_executed    ON candidate_trades(executed);
CREATE INDEX IF NOT EXISTS idx_suppression ON candidate_trades(suppression_reason);
CREATE INDEX IF NOT EXISTS idx_resolved    ON candidate_trades(resolved_direction);
